/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendorsRouteImport } from './routes/_app.vendors'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSodRouteImport } from './routes/_app.sod'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPaymentsRouteImport } from './routes/_app.payments'
import { Route as AppJournalsRouteImport } from './routes/_app.journals'
import { Route as AppFindingsRouteImport } from './routes/_app.findings'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChangesRouteImport } from './routes/_app.changes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSodRoute = AppSodRouteImport.update({
  id: '/sod',
  path: '/sod',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalsRoute = AppJournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => AppRoute,
} as any)
const AppFindingsRoute = AppFindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChangesRoute = AppChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/changes': typeof AppChangesRoute
  '/dashboard': typeof AppDashboardRoute
  '/findings': typeof AppFindingsRoute
  '/journals': typeof AppJournalsRoute
  '/payments': typeof AppPaymentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sod': typeof AppSodRoute
  '/users': typeof AppUsersRoute
  '/vendors': typeof AppVendorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/changes': typeof AppChangesRoute
  '/dashboard': typeof AppDashboardRoute
  '/findings': typeof AppFindingsRoute
  '/journals': typeof AppJournalsRoute
  '/payments': typeof AppPaymentsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sod': typeof AppSodRoute
  '/users': typeof AppUsersRoute
  '/vendors': typeof AppVendorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/changes': typeof AppChangesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/findings': typeof AppFindingsRoute
  '/_app/journals': typeof AppJournalsRoute
  '/_app/payments': typeof AppPaymentsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sod': typeof AppSodRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/vendors': typeof AppVendorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/login'
    | '/changes'
    | '/dashboard'
    | '/findings'
    | '/journals'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/sod'
    | '/users'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/login'
    | '/changes'
    | '/dashboard'
    | '/findings'
    | '/journals'
    | '/payments'
    | '/reports'
    | '/settings'
    | '/sod'
    | '/users'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_app'
    | '/login'
    | '/_app/changes'
    | '/_app/dashboard'
    | '/_app/findings'
    | '/_app/journals'
    | '/_app/payments'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/sod'
    | '/_app/users'
    | '/_app/vendors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sod': {
      id: '/_app/sod'
      path: '/sod'
      fullPath: '/sod'
      preLoaderRoute: typeof AppSodRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments': {
      id: '/_app/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journals': {
      id: '/_app/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof AppJournalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/findings': {
      id: '/_app/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof AppFindingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/changes': {
      id: '/_app/changes'
      path: '/changes'
      fullPath: '/changes'
      preLoaderRoute: typeof AppChangesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChangesRoute: typeof AppChangesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFindingsRoute: typeof AppFindingsRoute
  AppJournalsRoute: typeof AppJournalsRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSodRoute: typeof AppSodRoute
  AppUsersRoute: typeof AppUsersRoute
  AppVendorsRoute: typeof AppVendorsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChangesRoute: AppChangesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFindingsRoute: AppFindingsRoute,
  AppJournalsRoute: AppJournalsRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSodRoute: AppSodRoute,
  AppUsersRoute: AppUsersRoute,
  AppVendorsRoute: AppVendorsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
